# Generated by Django 5.1 on 2025-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_order_itemsprice_alter_order_paidat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='receivedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
