# Generated by Django 5.1 on 2025-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_isreceived_order_receivedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPreparing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preparingAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
