# Generated by Django 5.1 on 2025-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order_ispreparing_order_preparingat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPreparing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preparingAt',
        ),
        migrations.AddField(
            model_name='order',
            name='isOutForDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='outForDeliveryAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
