# Generated by Django 5.1 on 2025-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_order_ispreparing_remove_order_preparingat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='outForDeliveryAt',
        ),
        migrations.AddField(
            model_name='order',
            name='outForDeliveryInMinutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
