# Generated by Django 5.1 on 2025-04-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_order_outfordeliveryat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapinozz',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.order',),
        ),
    ]
