# Generated by Django 5.1 on 2025-04-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_lapinozz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lapinozz',
        ),
        migrations.CreateModel(
            name='LaPinozz',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.order')),
            ],
            options={
                'verbose_name': 'LaPinozz Order',
                'verbose_name_plural': 'LaPinozz Orders',
            },
            bases=('base.order',),
        ),
    ]
