# Generated by Django 5.1 on 2025-04-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_lapinozz_lapinozz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaPinozz',
        ),
    ]
