# Generated by Django 5.1 on 2025-04-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_delete_lapinozz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaPinozz',
            fields=[
            ],
            options={
                'verbose_name': 'La Pinozz Order',
                'verbose_name_plural': 'La Pinozz Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
    ]
