# Generated by Django 5.1 on 2025-04-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_lapinozz_lapinozz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='LaPinozz',
        ),
    ]
