# Generated by Django 5.1 on 2025-04-17 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_order_restaurant_delete_lapinozz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaPinozz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('original_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lapinozz_order', to='base.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
