# Generated by Django 5.1 on 2025-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_lapinozz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapinozz',
            name='original_order',
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='isOutForDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='isReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='itemsPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='outForDeliveryInMinutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='paidAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='receivedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='shippingPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='lapinozz',
            name='taxPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='lapinozz',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lapinozz',
            name='restaurant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
