# Generated by Django 5.1 on 2025-04-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_lapinozz_original_order_lapinozz_deliveredat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapinozz',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lapinozz_orders', to='base.order'),
        ),
    ]
