# Generated by Django 5.1 on 2025-04-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_burgerking_dominospizza_karnavatidabeli_lamilano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burgerking',
            options={'permissions': [('can_access_BurgerKing', 'Can access Burger King orders')]},
        ),
        migrations.AlterModelOptions(
            name='dominospizza',
            options={'permissions': [('can_access_DominosPizza', "Can access Domino's Pizza orders")]},
        ),
        migrations.AlterModelOptions(
            name='karnavatidabeli',
            options={'permissions': [('can_access_KarnavatiDabeli', 'Can access Karnavati Dabeli orders')]},
        ),
        migrations.AlterModelOptions(
            name='lamilano',
            options={'permissions': [('can_access_LaMilano', 'Can access La Milano orders')]},
        ),
        migrations.AlterModelOptions(
            name='lapinozz',
            options={'permissions': [('can_access_Lapinoz', "Can access La Pino'z orders")]},
        ),
        migrations.AlterModelOptions(
            name='pavbhaji',
            options={'permissions': [('can_access_PavBhaji', 'Can access Pav Bhaji orders')]},
        ),
        migrations.AlterModelOptions(
            name='shreemarutinandan',
            options={'permissions': [('can_access_ShreeMarutinandan', 'Can access Shree Marutinandan orders')]},
        ),
        migrations.AlterModelOptions(
            name='streetfood',
            options={'permissions': [('can_access_StreetFood', 'Can access Street Food orders')]},
        ),
    ]
