# Generated by Django 5.1 on 2025-04-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_burgerking_options_alter_dominospizza_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapinozz',
            name='isPaid',
        ),
    ]
