# Generated by Django 5.1 on 2025-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_lapinozz_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapinozz',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
