# Generated by Django 5.1 on 2025-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_lapinozz_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapinozz',
            name='isPaid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
