# Generated by Django 5.1 on 2025-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_lapinozz_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapinozz',
            name='isPaid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lapinozz',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
