# Generated by Django 5.1 on 2025-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_lapinozz_ispaid_alter_lapinozz_paidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapinozz',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lapinozz',
            name='paidAt',
            field=models.DateTimeField(null=True),
        ),
    ]
